export const DEMO_FLOATING_FILES = Object.freeze([
  {
    id: "floating-demo-plan",
    name: "研究计划.md",
    type: "Markdown",
    kind: "file",
    status: "已登记",
    invalid: false,
    favorite: true,
    size: 24_576,
    modifiedAt: 1_787_883_840,
    lastOpenedAt: 1_787_883_900,
    groupId: "floating-demo-research",
    groupName: "研究资料",
  },
  {
    id: "floating-demo-notes",
    name: "访谈记录.txt",
    type: "文本文件",
    kind: "file",
    status: "已登记",
    invalid: false,
    favorite: false,
    size: 8_192,
    modifiedAt: 1_787_881_200,
    lastOpenedAt: null,
    groupId: "floating-demo-research",
    groupName: "研究资料",
  },
  {
    id: "floating-demo-notes-copy",
    name: "访谈记录.txt",
    type: "文本文件",
    kind: "file",
    status: "已登记",
    invalid: false,
    favorite: false,
    size: 10_240,
    modifiedAt: 1_787_880_000,
    lastOpenedAt: null,
    groupId: "floating-demo-research",
    groupName: "研究资料",
  },
  {
    id: "floating-demo-sheet",
    name: "数据汇总.xlsx",
    type: "Excel 工作簿",
    kind: "file",
    status: "已登记",
    invalid: false,
    favorite: true,
    size: 86_016,
    modifiedAt: 1_787_879_700,
    lastOpenedAt: 1_787_883_600,
    groupId: "floating-demo-work",
    groupName: "项目资料",
  },
  {
    id: "floating-demo-folder",
    name: "资料归档",
    type: "文件夹",
    kind: "folder",
    status: "已登记",
    invalid: false,
    favorite: false,
    size: null,
    modifiedAt: 1_787_817_120,
    lastOpenedAt: null,
    groupId: "floating-demo-work",
    groupName: "项目资料",
  },
  {
    id: "floating-demo-image",
    name: "会议白板.png",
    type: "图片",
    kind: "file",
    status: "已登记",
    invalid: false,
    favorite: false,
    size: 1_048_576,
    modifiedAt: 1_787_816_400,
    lastOpenedAt: 1_787_820_000,
    groupId: null,
    groupName: null,
  },
  {
    id: "floating-demo-docx",
    name: "项目报价单.docx",
    type: "Word 文档",
    kind: "file",
    status: "已登记",
    invalid: false,
    favorite: false,
    size: 204_800,
    modifiedAt: 1_787_812_320,
    lastOpenedAt: null,
    groupId: "floating-demo-work",
    groupName: "项目资料",
  },
  {
    id: "floating-demo-missing",
    name: "旧项目资料（路径失效）",
    type: "文本文件",
    kind: "file",
    status: "路径失效",
    invalid: true,
    favorite: false,
    size: null,
    modifiedAt: null,
    lastOpenedAt: null,
    groupId: null,
    groupName: null,
  },
  {
    id: "floating-demo-video",
    name: "产品演示.mp4",
    type: "视频",
    kind: "file",
    status: "已登记",
    invalid: false,
    favorite: false,
    size: 12_582_912,
    modifiedAt: 1_787_805_120,
    lastOpenedAt: null,
    groupId: "floating-demo-work",
    groupName: "项目资料",
  },
  {
    id: "floating-demo-long-name",
    name: "一份用于检查悬浮球布局的较长中文资料文件名称示例.md",
    type: "Markdown",
    kind: "file",
    status: "已登记",
    invalid: false,
    favorite: false,
    size: 4_096,
    modifiedAt: 1_787_798_640,
    lastOpenedAt: null,
    groupId: "floating-demo-research",
    groupName: "研究资料",
  },
  {
    id: "floating-demo-space-name",
    name: "研究 计划副本.md",
    type: "Markdown",
    kind: "file",
    status: "已登记",
    invalid: false,
    favorite: false,
    size: 6_144,
    modifiedAt: 1_787_797_920,
    lastOpenedAt: null,
    groupId: "floating-demo-research",
    groupName: "研究资料",
  },
]);
